vscode:
  extensions:
    - rocketseat.RocketseatReactNative@2.2.0:R1GKe6htx17bP/HX+6BUFQ==
    - rocketseat.RocketseatReactJS@2.2.0:CMZI2JF+9mcg15CoJkRPOQ==
    - PKief.material-icon-theme@3.9.2:xeHlNzPEF04yFqz/xKCD5w==
    - dracula-theme.theme-dracula@2.19.2:YGBEpb4XH7h9BBDzol1CBw==